# Generated by Django 4.1.3 on 2024-04-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='desciption',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
